# Generated by Django 4.1.2 on 2022-10-27 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Prompt_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='WEUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromptPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('content', models.CharField(max_length=270)),
                ('promptId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writersedgeapi.prompt')),
                ('prompt_typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writersedgeapi.prompt_type')),
                ('weuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='writersedgeapi.weuser')),
            ],
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_typeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writersedgeapi.prompt_type'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('content', models.CharField(max_length=270)),
                ('weuser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='writersedgeapi.weuser')),
            ],
        ),
    ]
